In [1]:
import numpy as np

A = np.array([[10, 2, -1, 27], [-3, -6, 2, -61.5], [1, 1, 5, -21.5]])
X = np.zeros((3,1))

print "Sistema Ecuaciones Propuesto:"
print "\t10X1 + 2X2 -X3 = 27\n\t-3X1 -6X2 + 2X3 = -61.5\n\tX1 + X2 + 5X3 = -21.5"
print "\nMatriz Aumentada del Sistema:"
print "Matriz A:"
print A

n = 3
for k in range(0, n-1):
	for i in range(k+1, n):
		factor = A[i,k] / (A[k,k] * 1.0)
		for j in range(k,n):
			A[i,j] = A[i,j] - factor * A[k,j]
		A[i,n] = A[i,n] - factor * A[k,n]


X[n-1] = A[n-1,n] / (A[n-1,n-1] * 1.0)

for i in range(n-1,-1,-1):
	sum = A[i,n]
	for j in range(i+1, n):
		sum = sum - A[i,j] * X[j]
	X[i] = sum / (A[i,i] * 1.0)


print "\n\n#", "-" * 31, "a) Eliminación Gauss Simple ", "-" * 31, "#"
print "Matriz A:"
print A

print "\nIncognitas:"
print X
print "\n#", "-" * 92, "#"

print "\n#","-" * 23, " b) Sustituir Incognitas en las Ecuaciones: ", "-" * 23 ,"#"
print "x1= %f\tx2= %f\tx3= %f"%(X[0], X[1], X[2])
print "\n10(%.1f) + 2(%.1f) -(%.1f) = %.1f" % (X[0], X[1], X[2], 10*X[0] + 2*X[1] - X[2]) 
print "-3(%.1f) - 6(%.1f) + 2(%.1f) = %.1f" % (X[0], X[1], X[2], -3*X[0] - 6*X[1] + 2*X[2])
print "%.1f + (%.1f) + 5(%.1f) = %.1f" % (X[0], X[1], X[2], X[0] + X[1] + 5*X[2])
print "\n#", "-" * 92, "#"

Sistema Ecuaciones Propuesto:
	10X1 + 2X2 -X3 = 27
	-3X1 -6X2 + 2X3 = -61.5
	X1 + X2 + 5X3 = -21.5

Matriz Aumentada del Sistema:
Matriz A:
[[ 10.    2.   -1.   27. ]
 [ -3.   -6.    2.  -61.5]
 [  1.    1.    5.  -21.5]]


# ------------------------------- a) Eliminación Gauss Simple  ------------------------------- #
Matriz A:
[[ 10.           2.          -1.          27.        ]
 [  0.          -5.4          1.7        -53.4       ]
 [  0.           0.           5.35185185 -32.11111111]]

Incognitas:
[[ 0.5]
 [ 8. ]
 [-6. ]]

# -------------------------------------------------------------------------------------------- #

# -----------------------  b) Sustituir Incognitas en las Ecuaciones:  ----------------------- #
x1= 0.500000	x2= 8.000000	x3= -6.000000

10(0.5) + 2(8.0) -(-6.0) = 27.0
-3(0.5) - 6(8.0) + 2(-6.0) = -61.5
0.5 + (8.0) + 5(-6.0) = -21.5

# -------------------------------------------------------------------------------------------- #
