In [1]:
import numpy as np
from opermat import *

print "\nSistema de Ecuaciones dado:"
print "2X2 + 5X3 = 9\n2X1 + X2 + X3 = 9\n3X1 + X2 = 10"
M = np.array([[0,2,5],[2,1,1],[3,1,0]], dtype= np.float64) 
B = np.array([[9],[9],[10]], dtype= np.float64)

print "\n#", "-" * 36, " a) Determinante: ", "-" * 35, "#"
op = OperMat()
print "\nMatriz Coeficientes [M]:"
print M
dg = op.det(M)
print "\nDeterminante (det(M))= ", dg
print "\n#", "-" * 92, "#"


print "\n#", "-" * 35, " b) Valor Incognitas ", "-" * 34, "#"
print "\nMatriz Coeficientes del Sistema [M]:"
print M
print "\nDeterminantes:"

m, n = M.shape
det = []
for i in range(0, m):
	T = np.copy(M)
	for j in range(0, n):
		T[j,i] = B[j,0]
	
	print "\n","*" * 4
	print T
	det.append(op.det(T))
	print "\n\td%d= %.2f" % (i+1,det[i])
	det[i] /= dg


print "\nValores de Incognitas:"
print "X1= %.2f\tX2= %.2f\tX3= %.2f" % (det[0], det[1], det[2])
print "\n#", "-" * 92, "#"


print "\n#", "-" * 27, " c) Sustituyendo Valores Incognitas ", "-" * 27, "#"
print "\nSistema Ecuaciones:"
print "2X2 + 5X3 = 9\n2X1 + X2 + X3 = 9\n3X1 + X2 = 10"

print "\nValores de Incognitas:"
print "X1= %.2f\tX2= %.2f\tX3= %.2f" % (det[0], det[1], det[2])

print "\nSustituyendo: "
print "2(%.2f) + 5(%.2f) = %.2f" % (det[1], det[2], 2*det[1] + 5*det[2])
print "2(%.2f) + (%.2f) + (%.2f) = %.2f" % (det[0], det[1], det[2], 2*det[0] + det[1] + det[2])
print "3(%.2f) + (%.2f) = %.2f" % (det[0], det[1], 3*det[0]+ det[1])
print "\n#", "-" * 92, "#"



Sistema de Ecuaciones dado:
2X2 + 5X3 = 9
2X1 + X2 + X3 = 9
3X1 + X2 = 10

# ------------------------------------  a) Determinante:  ----------------------------------- #

Matriz Coeficientes [M]:
[[ 0.  2.  5.]
 [ 2.  1.  1.]
 [ 3.  1.  0.]]

Determinante (det(M))=  1.0

# -------------------------------------------------------------------------------------------- #

# -----------------------------------  b) Valor Incognitas  ---------------------------------- #

Matriz Coeficientes del Sistema [M]:
[[ 0.  2.  5.]
 [ 2.  1.  1.]
 [ 3.  1.  0.]]

Determinantes:

****
[[  9.   2.   5.]
 [  9.   1.   1.]
 [ 10.   1.   0.]]

	d1= 6.00

****
[[  0.   9.   5.]
 [  2.   9.   1.]
 [  3.  10.   0.]]

	d2= -8.00

****
[[  0.   2.   9.]
 [  2.   1.   9.]
 [  3.   1.  10.]]

	d3= 5.00

Valores de Incognitas:
X1= 6.00	X2= -8.00	X3= 5.00

# -------------------------------------------------------------------------------------------- #

# ---------------------------  c) Sustituyendo Valores Incognit