In [1]:
import numpy as np
X = np.zeros((4,1))
#A = np.array([[3, -0.1, -0.2, 7.85, 1], [0.1, 7, -0.3, -19.3, 3], [0.3, -0.2, 10, 71.4, 5], [0.4, -0.223, 10.9, 71.2, 50]])
B=[]

n = int(input("Digite el numero de ecuaciones:"))
for i in range(n):
    print "ingrese la Ecuacion "+str(i+1)
    B.append([])
    for j in range(n):
        ki = int(input("X "+str(j+1)+" "))
        B[i].append(ki)
        if j==(n-1):
            ki = int(input("ingresar el valor B: "))
            B[i].append(ki)
A=np.array(B)
print "Sistema Ecuaciones Propuesto:"
print "Matriz A:"
print A, "\n"

# Eliminación de Gauss Simple hacia adelante
for k in range(0, n-1):
    for i in range(k+1, n):
        factor = A[i,k] / (A[k,k] * 1.0)
        for j in range(k,n):
            A[i,j] = A[i,j] - factor * A[k,j]
        A[i,n] = A[i,n] - factor * A[k,n]
print "Resultados:"
print ""
print "Matriz A (Eliminacion hacia adelante):"
print A
# Sustitución hacia atrás
X[n-1] = A[n-1,n] / (A[n-1,n-1] * 1.0)

for i in range(n-1,-1,-1):
    sum = A[i,n]
    for j in range(i+1, n):
        sum = sum - A[i,j] * X[j]
    X[i] = sum / (A[i,i] * 1.0)

print "\n Matriz A (Sustitucion hacia atras):"
print X


Digite el numero de ecuaciones:4
ingrese la Ecuacion 1
X 1 1
X 2 -2
X 3 2
X 4 -3
ingresar el valor B: 15
ingrese la Ecuacion 2
X 1 3
X 2 4
X 3 -1
X 4 1
ingresar el valor B: -6
ingrese la Ecuacion 3
X 1 2
X 2 -3
X 3 2
X 4 -1
ingresar el valor B: 17
ingrese la Ecuacion 4
X 1 1
X 2 1
X 3 -3
X 4 -2
ingresar el valor B: -7
Sistema Ecuaciones Propuesto:
Matriz A:
[[ 1 -2  2 -3 15]
 [ 3  4 -1  1 -6]
 [ 2 -3  2 -1 17]
 [ 1  1 -3 -2 -7]] 

Resultados:

Matriz A (Eliminacion hacia adelante):
[[  1  -2   2  -3  15]
 [  0  10  -7  10 -51]
 [  0   0  -1   4  -7]
 [  0   0   0 -10   8]]

 Matriz A (Sustitucion hacia atras):
[[ 1.72]
 [-1.64]
 [ 3.8 ]
 [-0.8 ]]
